version: '3'
services:
  api-1:
    build: .
    ports:
      - 80
    depends_on:
      - redis
      - postgres
    command: sh -c "pm2-runtime ./src/server.js"
    links:
      - redis
      - postgres
    volumes:
      - .:/usr/app
  api-2:
    build: .
    ports:
      - 80
    depends_on:
      - redis
      - postgres
    command: sh -c "pm2-runtime ./src/server.js"
    links:
      - redis
      - postgres
    volumes:
      - .:/usr/app
  api-3:
    build: .
    ports:
      - 80
    depends_on:
      - redis
      - postgres
    command: sh -c "pm2-runtime ./src/server.js"
    links:
      - redis
      - postgres
    volumes:
      - .:/usr/app
  nginx:
    image: "nginx:stable"
    ports:
      - "80:80"
    links:
      - api-1
      - api-2
      - api-3
    depends_on:
      - api-1
      - api-2
      - api-3
    volumes:
      - "./deployment/nginx.conf:/etc/nginx/nginx.conf"
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:14-alpine"
    volumes:
      - "./deployment/shortener.sql:/docker-entrypoint-initdb.d/shortener.sql"
    environment:
      - POSTGRES_USER=shortener
      - POSTGRES_PASSWORD=secret
